name: silhouette
description: >-
  A simple template engine built to be familiar to Dart developers.
version: 0.0.1
repository: https://github.com/dart_community/silhouette

environment:
  sdk: ^3.10.0

dependencies:
  meta: ^1.16.0

dev_dependencies:
  night_raven_insight: ^4.0.0
  path: ^1.8.0
  test: ^1.26.0
  yaml: ^3.1.0
